### ISSUE TITLE
dib_env.sh file in README is incorrect 

### ISSUE THREAD

**Issue by johnoloughlin** [pndaproject/pnda-dib-elements#16]
Hi Guys 
export ALL_ELEMENTS="\\$BASE_ELEMENTS \\$AGENT_ELEMENTS \\$DEPLOYMENT_BASE_ELEMENTS \\$DEPLOYMENT_TOOL \\$PNDA_ELEMENTS"

should be 

export ALL_ELEMENTS="$BASE_ELEMENTS $AGENT_ELEMENTS $DEPLOYMENT_BASE_ELEMENTS $DEPLOYMENT_TOOL $PNDA_ELEMENTS"

If not the following command will fail

disk-image-create vm $ALL_ELEMENTS -o $IMAGE_NAME.qcow2

**Comment by jgarnier** [comment]
thanks for your question @johnoloughlin , but as this is within cat > dib_env.sh <<EOF
EOF, we had to escape them.
